add_newline = false
command_timeout=4000

format = """
[╭─](red) $directory$git_branch$git_metrics$git_status$package$nodejs
[╰─](red) """

#right_format = """$username"""

#[╭──](purple) 
#$directory$git_branch$git_status$package$nodejs[$cmd_duration](bold cyan)
#[╰──](purple) """
#[╰─]

[cmd_duration]
format = "took [$duration]($style) "

[directory]
truncate_to_repo = true
style = "bold cyan"

[git_branch]
#symbol = " 
symbol = " "
style = "bold bright-purple"
format = "($style)[$symbol]($style)[$branch]($style) "

[git_status]
style = "bright-red"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"
format = "(\\[([+$added]($added_style))([-$deleted]($deleted_style))\\])"

[nodejs]
disabled = false
style = "green"
symbol = " "


[package]
disabled = false
display_private = true
#symbol = " "
symbol = " "
style = "bold green"

[time]
disabled = false
style = "bold yellow"

[username]
disabled = false
show_always = true
format="[ $user]($style)"

[aws]
symbol = " "

[docker_context]
symbol = " "

[memory_usage]
symbol = " "

[python]
symbol = " "
detect_files=[".python-version", "Pipfile", "__init__.py", 
"pyproject.toml", "requirements.txt", "setup.py", "app.py"]

[rust]
symbol = " "
